---
title: "Solutions to STATS 506 Problem Set 1, Question 3"
author: "Alex Xiao"
date: 09/20/2019 
output: pdf_document
---
 
  This document provides my answer to the mouse-tracking problem. For sub-questions (a)-(e), every sub-question is answered with a function. For sub-question (f), a "table"(which is actually a matrix) with all the answers included is shown. For more details, check the notes before each solution.  

---
# Solution to problem 3a

  In this problem, the input **traj** (stands for "trajection") is a n $\times$ 3 matrix, with its first two columns stand for the position, **(x,y)**, while the third stands for the time, **t**. The output, **traj_trans**, is a translation of the former matrix, with time starting from 0 and position starting at the origin.  
  
  The function definition is shown below:  
  
```r

translate=function(traj){
  x_start=traj[1,1]
  y_start=traj[1,2]
  t_start=traj[1,3]
  traj_trans=traj
  starts=c(x_start,y_start,t_start)
  for(i in 1:nrow(traj)){
    for(j in 1:3){
      traj_trans[i,j]=traj[i,j]-starts[j]
    }
  }
  return(traj_trans)
}

```


# Solution to problem 3b

  Now that the data is translated, the input **traj** of this problem should still be a n $\times$ 3 matrix, but with its first row being (0,0,0). The output we are looking for, $\theta$, is the angle formed by the secant line connecting the origin and the final position. In this solution, $\theta$ is in the scale of radians and values between $-\pi$ and $\pi$.  
  
  The function definition is shown below:  
  
```r

angle_compute=function(traj){
  final=nrow(traj)
  theta=acos(traj[final,1]/sqrt(traj[final,1]^2+traj[final,2]^2))*sign(traj[final,2])
  return(theta)
}

```


# Solution to problem 3c

  In this problem we are still dealing with the matrix **traj**, but a translated version. We also have the rotate angle $\theta$, so it should be possible to rotate the points so that the final point lies on the x-axis.  
  
  In analytic geometry, the rotate formula can be expressed as     
          $$x'=xcos\theta+ysin\theta$$  $$y'=ycos\theta-xsin\theta$$ 
  The output **traj_rotate** can be thus computed, calling function *angle_compute()* defined in sub-question (b). Note that the y-value of the final spot might be a minute number due to approximate calculations, so you may use `round(rotate(input),n)` to check the results, where n is a (rather small) positive integer.   
  
  The function definition is shown below:  
  
```r

rotate=function(traj){
  theta=angle_compute(traj)
  traj_rotate=traj
  for(i in 1:nrow(traj)){
    traj_rotate[i,1]=traj[i,1]*cos(theta)+traj[i,2]*sin(theta)
    traj_rotate[i,2]=traj[i,2]*cos(theta)-traj[i,1]*sin(theta)
  }
  return(traj_rotate)
}

```


# Solution to problem 3d

  Combine the solution to the first three questions to get an integrated version, where the input **traj** is still an ordinary n $\times$ 3 matrix, and the output **traj_norm** is the normalized matrix which begins at the origin with time 0 and ends on the positive x-axis. Here I will provide a function that calls the previous functions.   
  
  The function definition is shown below:  
  
```r

normalize=function(traj){
  traj_trans=translate(traj)
  traj_norm=rotate(traj_trans)  
  return(traj_norm)
}

```
<!-- This is a version that calls the functions from sub-questions (a)-(c). Things should be similar for a function that does the same work without calling any of the previous functions,and the none-calling version would merely be a matter of copy and paste from the other functions defined above.-->


# Solution to problem 3e

  In this problem, the input **traj** is already normalized. The following lines denotes the outputs according to the description.  
  
  1)**dist**--the total (Euclidean) distance traveled.  
  2)**max_dev**--the maximum absolute deviation from the secant.  
  3)**ave_dev**--the average absolute deviation of the observed trajectory from the direct path.  
  4)**area**--the absolute area under the curve for the trajectory relative to the secant line.  
  
  The function definition is shown below:  

```r

metric_calc=function(traj){
  index=nrow(traj)
  dist_step=rep(0,index-1)
  for(i in 2:index){
    dist_step[i-1]=sqrt((traj[i,1]-traj[i-1,1])^2+(traj[i,2]-traj[i-1,2])^2)
  }
  dist=sum(dist_step)
  max_dev=max(abs(traj[,2]))
  ave_dev=mean(abs(traj[,2]))
  area_step=rep(0,index-1)
  for(i in 2:index){
    area_step[i-1]=(abs(traj[i,2])+abs(traj[i-1,2]))*(traj[i,1]-traj[i-1,1])/2
  }
  area=sum(area_step)
  result_list=c(dist,max_dev,ave_dev,area)
  return(result_list) 
}

```
  
  
# Solution to problem 3f

  First, use the train sets to verify the functions defined. Since the number of digits of the true values are uncertain (and unequal), both the computed metrics and the true values are rounded to the tenth digit before comparing. This may introduce some error but is GENERALLY helpful in checking.  
  
```r

train=read.csv("train_trajectories.csv",header=TRUE)
tres=read.csv("train_measures.csv",header=TRUE)
subs=max(train[,1])
trials=max(train[,2])
eq=matrix(NA,nrow=trials,ncol=subs)
for(i in 1:subs){
  for(j in 1:trials){
    tset=train[train[,1]==i&train[,2]==j,3:5]
    if(dim(tset)[1]==0) next
    print(paste("Testing subject",i,",trial",j,"."))
    train_res=metric_calc(normalize(tset));print(train_res)
    eq[j,i]=all(round(tres[tres[,1]==i&tres[,2]==j,3:6],1)==round(train_res,1))
  }
}

```

  The matrix **eq** shows if the values are equal. For those sets of subject-trial indices which do not exist, the corresponding elements take the value NA. All other values in the matrix turned out to be "TRUE".  
  
  Now it is time that we compute the metrics of the test sets. The output **metrics** is a n $\times$ 4 matrix concerning the traits in sub-question (e), where n stands for the total number of trials.  
  
  The solution is as follows:  

```r

test=read.csv("test_trajectories.csv",header=TRUE)
test_subs=intersect(test[,1],test[,1])
test_trials=intersect(test[,2],test[,2])
a=length(test_subs);b=length(test_trials);n=a*b
tlist=matrix(NA,nrow=a,ncol=b)
for(i in 1:a){
  for(j in 1:b){
    tlist[i,j]=paste("Sub",test_subs[i],"Trial",test_trials[j])
  }
}
metrics=matrix(NA,nrow=length(tlist),ncol=4,dimnames=list(tlist,c("dist","max_dev","ave_dev","area")))
for(i in 1:a){
  for(j in 1:b){
    testset=test[test[,1]==test_subs[i]&test[,2]==test_trials[j],3:5]
    if(dim(testset)[1]==0) next
    print(paste("Testing subject",test_subs[i],",trial",test_trials[j],"."))
    test_res=metric_calc(normalize(testset));print(test_res)
    metrics[b*(i-1)+j,]=test_res
  }
}
(metrics=metrics[complete.cases(metrics),])

```

<!--`intersect()` is used to get a set of the subjects and trials. For now this is the best solution I could come up with.-->


  The table can also be viewed directly below:
  
  |  Subject/Trial  | Eucildian distance | maximum deviation | average deviation | area under curve |
  |:---------------:|:------------------:|:-----------------:|:-----------------:|:----------------:|
  |  Sub 6 Trial 1  |     1650.769       |     464.89910     |     90.387825     |    275254.35     |
  |  Sub 7 Trial 1  |     1252.550       |      35.46823     |      4.723562     |     19981.20     |
  |  Sub 8 Trial 1  |     1069.158       |      18.41130     |      1.757015     |     10133.99     |
  |  Sub 9 Trial 1  |     1092.076       |      74.20550     |      7.302945     |     36134.40     |
  | Sub 10 Trial 1  |     1086.835       |      85.33933     |     12.487715     |     51446.32     |
  
  
  
  


  

  
